In [77]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [80]:
data2 = pd.DataFrame([
['Male', 37],
['Female', 32],
['Other', 41],
['Male', 56]
], columns=['Gender','Age'])

In [68]:
encoder = OneHotEncoder(sparse_output=False, dtype=int)
encoder.fit_transform(data2[['Gender']])

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [69]:
encoder = OneHotEncoder(sparse_output=False, dtype=int, drop='first')
encoder.fit_transform(data2[['Gender']])

array([[1, 0],
       [0, 0],
       [0, 1],
       [1, 0]])

In [70]:
pd.get_dummies(data=data2, columns=['Gender'],dtype=int)

   Age  Gender_Female  Gender_Male  Gender_Other
0   37              0            1             0
1   32              1            0             0
2   41              0            0             1
3   56              0            1             0

In [71]:
pd.get_dummies(data=data2, columns=['Gender'],dtype=int, drop_first=True)

   Age  Gender_Male  Gender_Other
0   37            1             0
1   32            0             0
2   41            0             1
3   56            1             0

In [12]:
datal = pd.DataFrame([
        [58, 1.52, 7],
        [57, 1.53, 6],
        [60, 1.7, 5.8],
        [70, 1.69, 8],
        [65, 1.66, 9]
    ], columns=['Weight', 'Height', 'Score'])
datal

   Weight  Height  Score
0      58    1.52    7.0
1      57    1.53    6.0
2      60    1.70    5.8
3      70    1.69    8.0
4      65    1.66    9.0

In [14]:
datal['bias'] = [1] * datal.shape[0]
datal

   Weight  Height  Score  bias
0      58    1.52    7.0     1
1      57    1.53    6.0     1
2      60    1.70    5.8     1
3      70    1.69    8.0     1
4      65    1.66    9.0     1

In [15]:
Xhat = datal[['bias','Weight', 'Height']].values
y = datal['Score'].values

In [16]:
Xhat.shape, y.shape

((5, 3), (5,))

$$\beta = (X^T * X)^{-1} * (X^T *y)$$

In [17]:
np.linalg.inv(Xhat.T @ Xhat) @ (Xhat.T @ y)

array([ 2.14550334,  0.26170344, -6.92044242])

In [18]:
beta = np.linalg.inv(Xhat.T @ Xhat) @ (Xhat.T @ y)
beta

array([ 2.14550334,  0.26170344, -6.92044242])

### Du doan voi weught = 56 va height = 1.4
$$\beta_0 + \beta_1 * weight + \beta_2 * height$$

In [20]:
Xt = np.array([1, 56, 1.4])
predict = beta @ Xt.T
print('Predict', predict)

Predict 7.112276682948073

In [21]:
y_predict=Xhat @ beta.T
y_predict

array([6.80523048, 6.47432261, 6.08295772, 8.76919656, 7.66829263])

### Mean Square Error
$$mse = \frac{\sum{(y_i - y_predict)^2}}{n}$$

In [22]:
mse = sum((y - y_predict)**2) / y.shape[0]
print('Mean Square Error', mse)

Mean Square Error 0.5416180113413059

$$R^2 = 1 - \frac{\sum(y_1 - ypre_i)^2}{\sum(y_i - \bar{y})^2}$$

In [23]:
r2 = 1 - sum((y - y_predict)**2) / sum((y - np.mean(y))**2)
print('R^2 score', r2)

R^2 score 0.6296375743016235

In [24]:
X = datal[['Weight', 'Height']].values
y= datal['Score'].values
lg= LinearRegression()
lg.fit(X,y)
lg.intercept_,lg.coef_

(np.float64(2.1455033406322057), array([ 0.26170344, -6.92044242]))

In [25]:
y_pred = lg.predict(X)
r2_score(y, y_pred), lg.score(X,y)

(0.6296375743016234, 0.6296375743016234)

In [27]:
mean_squared_error(y, y_pred)

0.541618011341306

In [28]:
## load du lieu tu tap tin

In [62]:
df = pd.read_csv('data/BostonHousing.csv')
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [63]:
X= df.drop(columns='medv')
y= df['medv']

In [9]:
## chia tap du lieu thanh 2 phan 75% la train, 25% la test

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [65]:
lg = LinearRegression()
lg.fit(X_train,y_train)
lg.score(X_train,y_train), lg.score(X_test,y_test)

(0.7365737361377328, 0.7216363514308912)

In [ ]:
##load dữ liệu từ tập tin csv

In [96]:
df= pd.read_csv('data/Salary_Data.csv')
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

In [97]:
df.shape, df.isna().sum()

((6704, 6),
 Age                    2
 Gender                 2
 Education Level        3
 Job Title              2
 Years of Experience    3
 Salary                 5
 dtype: int64)

In [ ]:
## Kiểm tra dữ liệu có null ko?
### do dữ liệu có giá trị null nhiều => chọn giải pháp xóa các dòng null

In [98]:
100 - (df.dropna().shape[0] * 100 / df.shape[0])

0.08949880668258459

In [99]:
df.dropna(inplace=True)

In [100]:
df.shape, df.isna().sum()

((6698, 6),
 Age                    0
 Gender                 0
 Education Level        0
 Job Title              0
 Years of Experience    0
 Salary                 0
 dtype: int64)

In [49]:
## tien xu ly tren cot Education Level

In [101]:
df['Education Level'].value_counts

<bound method IndexOpsMixin.value_counts of 0              Bachelor's
1                Master's
2                     PhD
3              Bachelor's
4                Master's
              ...
6699                  PhD
6700          High School
6701    Bachelor's Degree
6702      Master's Degree
6703          High School
Name: Education Level, Length: 6698, dtype: object>

In [102]:
def clean_education_level(text):
    if text == 'phD':
        return 'PhD'
    if text == "Master's":
        return "Master's Degree"
    if text == "Bachelor's":
        return "Bachelor's Degree"
    return text
df['Education Level'].map(clean_education_level).value_counts()

Education Level
Bachelor's Degree    3021
Master's Degree      1860
PhD                  1369
High School           448
Name: count, dtype: int64

In [103]:
df['Gender'].value_counts

<bound method IndexOpsMixin.value_counts of 0         Male
1       Female
2         Male
3       Female
4         Male
         ...
6699    Female
6700      Male
6701    Female
6702      Male
6703    Female
Name: Gender, Length: 6698, dtype: object>

In [104]:
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

In [105]:
df2= pd.get_dummies(data = df, columns=['Gender'], dtype=int)
df2.head()

,Age,Education Level,Job Title,Years of Experience,Salary,Gender_Female,Gender_Male,Gender_Other
0,32.0,Bachelor's,Software Engineer,5.0,90000.0,0,1,0
1,28.0,Master's,Data Analyst,3.0,65000.0,1,0,0
2,45.0,PhD,Senior Manager,15.0,150000.0,0,1,0
3,36.0,Bachelor's,Sales Associate,7.0,60000.0,1,0,0
4,52.0,Master's,Director,20.0,200000.0,0,1,0

In [106]:
df2.columns

Index(['Age', 'Education Level', 'Job Title', 'Years of Experience', 'Salary',
       'Gender_Female', 'Gender_Male', 'Gender_Other'],
      dtype='object')

In [109]:
X= df2[['Age','Gender_Female','Gender_Male','Gender_Other']].values
y= df2['Salary'].values
lg= LinearRegression()
lg.fit(X,y)
lg.intercept_,lg.coef_,lg.score(X,y)

(np.float64(-59888.217847079984),
 array([  5016.30673209,   4113.75794498,   8630.59060652, -12744.3485515 ]),
 0.5321420698986449)

In [110]:
X= df2[['Age','Gender_Male','Gender_Other']].values
y= df2['Salary'].values
lg= LinearRegression()
lg.fit(X,y)
lg.intercept_,lg.coef_,lg.score(X,y)

(np.float64(-55774.4599021047),
 array([  5016.30673209,   4516.83266155, -16858.10649647]),
 0.5321420698986449)

In [111]:
X= df2[['Age','Gender_Female','Gender_Male','Gender_Other']].values
y= df2['Salary'].values
X_train, X_test, y_train, y_test = train_test_split(X,y)
lg = LinearRegression()
lg.fit(X_train,y_train)
lg.intercept_,lg.coef_,lg.score(X_train,y_train), lg.score(X_test,y_test)

(np.float64(-60408.28812052423),
 array([  4966.95884266,   7022.65069099,  10980.10254761, -18002.75323861]),
 0.5228711002414859,
 0.5582540099555563)

In [112]:
X= df2[['Age','Gender_Male','Gender_Other']].values
y= df2['Salary'].values
X_train, X_test, y_train, y_test = train_test_split(X,y)
lg = LinearRegression()
lg.fit(X_train,y_train)
lg.intercept_,lg.coef_,lg.score(X_train,y_train), lg.score(X_test,y_test)

(np.float64(-55643.782080246965),
 array([  5016.15422871,   4664.58631168, -22749.03383388]),
 0.5351522376703306,
 0.5201885671645796)

## Tiền xử lý Job Title

In [126]:
df['Job Title'].value_counts

<bound method IndexOpsMixin.value_counts of 0           Software Engineer
1                Data Analyst
2              Senior Manager
3             Sales Associate
4                    Director
                ...
6699    Director of Marketing
6700          Sales Associate
6701        Financial Manager
6702        Marketing Manager
6703          Sales Executive
Name: Job Title, Length: 6698, dtype: object>

xóa biến job title bởi vì giá trị quá nhiều khoảng 191 giá trị

In [128]:
df.drop(columns='Job Title', inplace=True)

Tiền xử lý cho education level

In [119]:
df['Education Level'] = df['Education Level'].map(clean_education_level)

In [122]:
df2 = pd.get_dummies(data=df,columns=['Gender','Education Level'], drop_first=True, dtype=int)
df2.head()

,Age,Job Title,Years of Experience,Salary,Gender_Male,Gender_Other,Education Level_High School,Education Level_Master's Degree,Education Level_PhD
0,32.0,Software Engineer,5.0,90000.0,1,0,0,0,0
1,28.0,Data Analyst,3.0,65000.0,0,0,0,1,0
2,45.0,Senior Manager,15.0,150000.0,1,0,0,0,1
3,36.0,Sales Associate,7.0,60000.0,0,0,0,0,0
4,52.0,Director,20.0,200000.0,1,0,0,1,0

In [121]:
x = df2.drop(columns=['Salary'])
y=df2['Salary']
X_train, X_test, y_train, y_test = train_test_split(X,y)
lg = LinearRegression()
lg.fit(X_train,y_train)
lg.score(X_train,y_train), lg.score(X_test,y_test)

(0.5290924934622971, 0.5408442977810847)